### ISSUE TITLE
wrong icon theme is copied

### ISSUE THREAD

**Issue by hkollmann** [qooxdoo/qooxdoo-compiler#131]
If you create an application with `qx create myapp -I  -v `

you get 
`qx.Theme.define("myapp.theme.Theme",
{
  meta :
  {
    color : myapp.theme.Color,
    decoration : myapp.theme.Decoration,
    font : myapp.theme.Font,
    icon : qx.theme.icon.Oxygen,
    appearance : myapp.theme.Appearance
  }
});`

after `qx compile` you have the Tango theme in resources:

`myapp\source-output\resource\qx\icon\Tango`????

**Comment by johnspackman** [comment]
There are two issues here - firstly, `qx create` should specify an icon theme in the theme and also specify an environment variable `qx.icontheme`; at the moment it is inconsistent, and either should have `icon: qx.theme.icon.Tango` or add `"environment": { "qx.icontheme": "Oxygen" }` in compile.json (setting `icon: qx.theme.icon.Tango` would be best because that's the default in 5.x)

Secondly, even when this was done it would make little or no difference - the Qooxdoo framework explicitly refers to `@asset(qx/icon/Tango/....` so Oxygen is effectively ignored.  According to the docs, it is possible to change these `@asset` tags to something like `@asset(qx/icon/${qx.icontheme}/...` but this does not work in the generator, eg it fails with:

```
>>> Warning: Warning: (qx.theme.indigo.Appearance): Cannot replace macro 'qx.icontheme' in @asset hint
>>> Warning: No resource matched @asset(qx/icon/${qx.icontheme}/16/actions/dialog-cancel.png) (qx.theme.simple.Appearance)
```

Yet the files exist:
```
$ find source/resource -name dialog-cancel.png
source/resource/qx/icon/Oxygen/16/actions/dialog-cancel.png
source/resource/qx/icon/Tango/16/actions/dialog-cancel.png
```

The `@asset(qx/icon/${qx.icontheme}/...` does work in the compiler, and the changes to the framework are relatively minor so if the generator can be fixed the this problem can be fixed also.

**Comment by hkollmann** [comment]
So to get Oxygen 2 places must be edited: the themes file and compile.json, right?

**Comment by cboulanger** [comment]
see also https://github.com/qooxdoo/qooxdoo/issues/9485

**Comment by johnspackman** [comment]
@hkollmann yes plus the qooxdoo framework files, and then the generator has to be fixed so that it can accept variables in the `@asset` tags (which it's supposed to be doing already)

**Comment by cboulanger** [comment]
As I have written in the  qooxdoo/qooxdoo#9485, the problem wouldn't exist if the framework used aliases instead of hard-coded (or even partly aliases) paths. If I had time, I'd create a PR replacing all paths with aliases, but unfortunately, I don'T...

**Comment by cboulanger** [comment]
In my view, icons shouldn't be in class files to begin with, it violates the DRY principle and makes changing icon sets impossible.

**Comment by hkollmann** [comment]
With the generator you get the oxygen theme with mention it in the themes class. Tango theme is not copied in this case. So you can use oxygen icons in your own classes

**Comment by johnspackman** [comment]
please can you check something for me - is it the case that (with the generator) if you use the Oxygen icon theme, the generator will *not* include the `qx/icon/Tango/*` files, even though they are specified by `@asset` directives, and instead choose the `Oxygen` equivalents?

**Comment by hkollmann** [comment]
Will do so on sunday - only ipad avaible yet

**Comment by hkollmann** [comment]
compiled with generaty.py
`
+---Oxygen
|   +---16
|   |   +---actions
|   |   +---apps
|   |   +---mimetypes
|   |   \---places
|   \---64
|       \---actions
\---Tango
    +---16
    |   +---actions
    |   +---apps
    |   +---mimetypes
    |   \---places
    +---22
    |   +---mimetypes
    |   \---places
    \---32
        +---mimetypes
        \---places
`
compiled with qx:
`
\---Tango
    +---16
    |   +---actions
    |   +---apps
    |   +---mimetypes
    |   \---places
    +---22
    |   +---mimetypes
    |   \---places
    +---32
    |   +---mimetypes
    |   \---places
    \---64
        \---actions
`

**Comment by hkollmann** [comment]
adding 
```
  "environment": { 
      "qx.icontheme": "Oxygen" 
  },     
```
does the trick. Both iconsets are copied.

One problem left: The icontheme must be metioned in two different places,

- compile.json

- Theme.js

Something like 
```
qx.Theme.define("vzaweb.theme.Theme", {
  meta : {
    color : vzaweb.theme.Color,
    decoration : vzaweb.theme.Decoration,
    font : vzaweb.theme.Font,
    icon : "qx.theme.icon.${qx.icontheme}",
    appearance : vzaweb.theme.Appearance
  }
});

```
is not possible.

**Comment by hkollmann** [comment]
Where do you get the warnings in the generator? If i changed @asset(qx/icon/Tango to @asset(qx/icon/${qx.icontheme} in the framework/source folder generate works fine for my project

**Comment by hkollmann** [comment]
Found the warning. It's generated during creating the apiviewer.
Question is if we can change the framework and ignore the warning.

**Comment by johnspackman** [comment]
aha, I just saw all the warnings and assumed it was the app generation.

I'm still confused though - I don't get how the generator knows to switch to different icon sets, because I can't find any reference to `qx.icontheme` in the JS code, and when it *does* switch to Oxygen that means that it should only copy Oxygen icons ...

**Comment by hkollmann** [comment]
this will be done with https://github.com/qooxdoo/qooxdoo/pull/9495

**Comment by hkollmann** [comment]
Working and qooxdoo path is merged. Thanks  @johnspackman !
