### ISSUE TITLE
"Clone" build targets

### ISSUE THREAD

**Issue by cboulanger** [qooxdoo/qooxdoo-compiler#166]
Following use case: 

I have two different `build` targets, which have different `environment` settings (one to test a build locally, within the source code, and one that will be used for a distributed build). I need different build targets for them, but don't know if this is already supported in the current system.

What I would need is a way of "cloning" the `build` target and just replace the `environment`. How would I do that, or, if it is currently not possible, could such a feature be implemented easily?

**Comment by johnspackman** [comment]
There's two things here: (a) to be able to synthesise configuration blocks according to some rule(s), and (b) to be able to specify multiple targets of the same type.

For (a), this can be achieved by using a `compile.js` to either output the configuration structure or to add some kind of processing on the `compile.json` so that you can do things like copy settings etc - see [here](https://github.com/qooxdoo/qooxdoo-compiler/blob/master/docs/cli/compile-json.md#compilejs) for more details

For (b), this is something that I thought I'd coded but looking at the code is not quite there yet; when looking at a `target: { type: "source" }` the value for `type` serves as both an identifier and says which class to use to create to do the compile; actually it does not have to be `"source"` or `"build"`, it can also be a class name ... but I think that this is kind of flawed.  

How about the `type` is just an identifier, and where a well-known value is given (ie "source" or "build") we use that to figure out the class name; but the class name can always be overridden by a new property eg `targetClass`.  

```
targets: [
   { 
      type: "source-abc", 
      targetClass: "qx.tool.compiler.targets.SourceTarget",
      environment: { someValue: "abc" }
   },
   { 
      type: "source-def", 
      targetClass: "qx.tool.compiler.targets.SourceTarget",
      environment: { someValue: "def" }
   },
   { 
      type: "source-ghi", 
      targetClass: "qx.tool.compiler.targets.SourceTarget",
      environment: { someValue: "ghi" }
   }
]
```

Incidentally, as a convenience, the current code automatically prepends "qx.tool.compiler.targets." to the class name if there is no package specified, so this is a more concise example:

```
targets: [
   { 
      type: "source-abc", 
      targetClass: "SourceTarget",
      environment: { someValue: "abc" }
   },
   { 
      type: "source-def", 
      targetClass: "SourceTarget",
      environment: { someValue: "def" }
   },
   { 
      type: "source-ghi", 
      targetClass: "SourceTarget",
      environment: { someValue: "ghi" }
   }
]
```

To implement this, I'm fairly sure that all you would need to do is to change these lines: https://github.com/qooxdoo/qooxdoo-compiler/blob/master/lib/qx/tool/cli/commands/Compile.js#L297-L299 to have this code:

```
      var targetClass = data.target.targetClass && this.resolveTargetClass(data.target.targetClass);
      if (!targetClass && data.target.type)
        targetClass = this.resolveTargetClass(data.target.type);
      if (!targetClass)
        throw new qx.tool.cli.Utils.UserError("Cannot find target class: " + (data.target.targetClass||data.target.type));

```

**Comment by cboulanger** [comment]
Thanks! I‘ll test that and provide a PR.

**Comment by cboulanger** [comment]
Issue is fixed, closing.
