### ISSUE TITLE
Translation messages in libraries should be taken from, and updated in library, not application

### ISSUE THREAD

**Issue by cboulanger** [qooxdoo/qooxdoo-compiler#175]
Current behaviour: When a library contains translated strings, the compile will insert them in the `.po` files of the main application which is being compiled, and take the translations from there.

Expected behaviour: Translation messages in libraries should be taken from, and updated in the `.po` files in the library's `translation` folder.

**Comment by derrell** [comment]
I'm not convinced that's always the expected behavior. If I'm using a contrib library in my app and I want to internationalize my app, I suspect I'd want at least an option to have all libraries' strings and all of my app's strings end up in a single .po file for me to translate, rather than having to go find each of the independent libraries' .po files and translate them. This just seems easier from an app-developer's point of view. I'm not sure whether the default is for the user (app developer) or for the developer of the library. I'd likely lean towards defaulting to putting all strings into the app's .po file, and having an option that a library developer could use to instead put them in library-specific .po files.

**Comment by cboulanger** [comment]
Good point. Although of course, the preferred way would be to contribute translations back to the library via a pull request. If we make it configurable, all use cases will be served.

**Comment by oetiker** [comment]
I would assume the expected behavior depends on the project type ... if it is a 'contrib' then the translations should go into the library. if it is a normal project, then the current behavior is fine.

**Comment by cboulanger** [comment]
What's the current opinion on the issue? Mine is:
- if the (package) library has translations, the compiler should take them from there, and not pollute the main app's po files with translations strings from other libraries. Ideally, message ids shoud be namespaced to avoid confusion, but that's another matter.
- if the main app's author provides a translations for a given message id, it should take precedence over the external library's message string

**Comment by hkollmann** [comment]
I agree

Von meinem iPad gesendet

**Comment by level420** [comment]
From my recent gitter question on how translations of libraries/packages should be handled:
For my use case it would be helpful to have the possibility to override translations from libraries. E.g. if I have somewhere in the lirary:
```
this.tr('goods');
```
And I'm using that library in 2 different apps, I'd like to be able to override that in the en translations of those apps. For the `foo` app with `foo goods` and for the `bar app` with `bar goods`.
