### ISSUE TITLE
Add testrunner Maker

### ISSUE THREAD

**Issue by johnspackman** [qooxdoo/qooxdoo-compiler#20]
Add a `qxcompiler.makers.Maker` for building test runner

**Comment by peuter** [comment]
I'm not sure if this is the right place, but as this issue is about testrunner I'll try it here;

The karma-qooxdoo adapter (used in travis to run qooxdoo's unit tests) does not work with code compiled with qx compiler.

Basically the adapter needs to access `qx.$$libraries` and `qx.$$loader` from the generated boot js.
The old way of getting this information was/is very ugly (regex in combination with eval) and is not possible with the code in boot.js. I guess the best way would be to generate a file with only the information needed, maybe that's what the purpose of this issue is about?

**Comment by johnspackman** [comment]
Kind of - the need for a "testrunner Maker" means that the generator had a lot of code (mostly in config files) that was used to detect which modules were needed and compile them, and along the way generate some other artifacts that were required for the test runner to operate.

This does mean that qxcompiler is not able to produce a testrunner right now, which is going to be an issue for you if you are using ES6 and relying on the transpilation in order to have working code.  Having a working qxcompiler-based TestRunner is a blocker, and is getting increasingly important.

I'm not sure whether you would be able to rig together something that worked with qxcompiler doing some bits and generator doing others - I can't look at it right now, but I'll do my best to help you figure it out if I can.  Please can you point me to the code you're talking about and I'll see if I can come up with an alternative?  

(BTW I'll be out most of this afternoon)

**Comment by peuter** [comment]
I added this comment, just as a reminder that the problem must be solved before the qooxdoo project replaces the old generator with the new compiler (because the tests on travis would fail then). 
I don't need it personally at this moment. So no reason to hurry ;-)

The code where the karma adapter extracts the information it needs from the loader script is here: https://github.com/qooxdoo/karma-qooxdoo/blob/master/karma-qooxdoo.js#L84-L91 (I know its ungly code).

If qx compiler will support loader templates I quess that should be the way to go: use a special loader template to generate a loader script for the karma adapter. But I am not really familiar with the qx compiler yet, maybe there is another, even better way.

**Comment by johnspackman** [comment]
ISWYM; the problem is not that the `qx.$$` variables have changed in structure, it's just that the loader data is formatted slightly differently - I think that the `libinfo` regex at https://github.com/qooxdoo/karma-qooxdoo/blob/master/karma-qooxdoo.js#L84 is failing because the JSON is not on one line; try changing it to:

```
    // read libinfo
    matches = source.match(/var libinfo = {((.|\n)*)};\n/m);
```

I think that if the second regex fails, it is because there is only one `\n` after the data structure, in which case please try tweaking `qxcompiler/lib/qxcompiler/app/loader-browser.tmpl.js`.

Ultimately the best way may be for the qxcompiler to output the data as a JSON file in the application directory alongside boot.js; it would be a duplicate of whats in `boot.js`, so should only enabled for the test runner output but would be much easier and more reliable to parse.  (actually the `SelfTestTarget` does exactly this so that the unit tests can check what qxcompiler calculated)

**Comment by johnspackman** [comment]
The next version of qx-cli supports a `writeCompileInfo` property for each target, that will cause a `compile-info.json` and `resources.json` to be output into each application directory, eg:

```
	/** Targets */
	"targets": [
		{
			"type": "source",
			"outputPath": "source-output",
			"writeCompileInfo": true
		}
```

**Comment by johnspackman** [comment]
Is this still necessary?  If the old testrunner been superceeded by @oetiker 's https://github.com/qooxdoo/qxl.testtapper we can close this

**Comment by cboulanger** [comment]
The old testrunner was nice to look at but I guess we don't need any eye candy if all we're interested in is if the tests pass or not (you can tell 1&1 had a team of 6+ developers to spend time on things like the test runner...)
