### ISSUE TITLE
Transpiled build code size very long compared to version 5.0.2

### ISSUE THREAD

**Issue by ecc7220** [qooxdoo/qooxdoo-compiler#295]
Compared javascript files from 5.0.2 project sums up to 1.1 MB in my case (only one file). Using 6.0.0-alpha-20181226-a3c2b0b and compiler 0.2.54 I get just for a few classes ported so far already 1.5 MB of file size, counting only part-0.js other files boot.js, resources.js and polyfill.js not included.

**Comment by cboulanger** [comment]
@johnspackman Is that still the case and is there anything that can be done about this, and if yes, would it happen before the release of v6.0.0?

**Comment by paragasu** [comment]
In my case the previous 5.0.2 generate about 2.1mb of js file. Ported into 6.0.0-alpha using qx compiler v0.3.0-alpha.20190430-1926 generate about 87mb files. 

(There is unoptimize resource directory full with icons svg files totaling about 21mb)

**Comment by johnspackman** [comment]
@paragasu Resources are transpiled as well as source code because some resources are created during the compilation process (eg image combine/split); this means that if you have a lot of resources, the output directory will be large, but OTOH the compiler will not modify the source code or resources, and means that the output directory is self contained (which greatly simplifies generation and hosting).

However, I would expect that only those resources which are required by the application are copied into the output directory; the compiler knows which resources you need by looking for `@asset` directives in your code, so for example if your application uses the `myapp` namespace and you have `@asset(myapp/*`) that will include *all* resources in your output directory.

In the output directory, the only things you need for deployment are the `resource` and `myapp` (or whatever you application is called) directories - everything else are temporary working files for the compiler.  

In 5.x and earlier, the generator would create a cache directory which was similarly big (actually it could be a *lot* bigger than 80Mb), and folders like `transpiled` have a similar purpose - without those temporary files, compiling would be very slow.

AFAIAA, there is an increase in .js code size as reported by @ecc7220, but that's 1.1Mb => 1.5Mb, which is nowhere near the increase of 2.1Mb -> 66Mb.  Please can you take a look and confirm where the extra disk usage is coming from?

**Comment by cboulanger** [comment]
The problem will go away if we have #296 implemented. As @johnspackman explained, the current directory structure makes visible what was before hidden by the generator, and makes use of more advanced javascript syntax feature (via Babel) possible - which the generator was unable to do.

**Comment by hkollmann** [comment]
closed with https://github.com/qooxdoo/qooxdoo-compiler/pull/654
