### ISSUE TITLE
add --deploy-to path/to/deploydir

### ISSUE THREAD

**Issue by ecc7220** [qooxdoo/qooxdoo-compiler#296]
The 5.0.2 version builds only one javascript and index.html plus resources. The new qx compiler puts plenty of other files into the build folder. They are not all needed for deployment and could cause a possible security issue, if installed as is.

**Comment by johnspackman** [comment]
There are a few files which have crept into the build that I don't understand why they're there - `app.png` (which is the Qooxdoo logo) and `js_256x256.png` (which is some kind of javascript logo).

Of the rest of the files the only ones which are not required are `build-data.json` and `*.map`; the `.map` files are part of the target and need to be there, although I agree that they would normally be excluded from your deployment process.  

Potentially we could add a `--deploy-to <directory>` option to `qx compile` which would copy the essential files to a deployment directory?

**Comment by ecc7220** [comment]
I agree, this would a good solution.

**Comment by sqville** [comment]
I agree as well

**Comment by derrell** [comment]
To add a bit more detail about this... The first application listed in `compile.json` is now the one whose `index.html` is copied to the root. Other necessary files, however, are not copied to the root, e.g., `favicon.png`, which means that if the app is accessed as `/myApp/index.html` the favicon shows on the tab, but if it's accessed as `/index.html`, the facicon is not shown on the tab.

**Comment by oetiker** [comment]
when building multiple apps it would be great to have a way to specify a separate index.html or rather a separate boot directory for it ...

one option would be to structure boot the same as the resources directory in that it has subdirectories per app and if the app is missing then it gets the defaul settings ... 

whatever is in the toplevel boot would end up in the root of the *-output tree

**Comment by cboulanger** [comment]
Updated title.

**Comment by johnspackman** [comment]
For first compile of a source target, how about we output a message to the console in big friendly letters saying that the build version will be much smaller?

**Comment by cboulanger** [comment]
Good idea. This will reach people who might not have read the info in the getting-started-guide.

An alternative to a deployment switch would be to output the paths to the directories containing the deployable code when using a "Build" target.

**Comment by cboulanger** [comment]
It has just been brought up on the main chat that source maps leak information on paths on the development machine. They should be excluded from the deployed source code bundle. This reinforces the idea that we should have a dedicated command to export deployable code. This would avoid that we have to document such internal stuff.

**Comment by cboulanger** [comment]
Maybe the most natural solution is to ship a separate compilation target `--target=deploy` which would automatically remove all unneeded code and copy stuff into, i.e., a `deploy` folder in the root (not under `compiled`)

**Comment by hkollmann** [comment]
Copy it into a folder compiled/deploy...

**Comment by cboulanger** [comment]
@johnspackman What would be the best way to create a deploy target that inherits from https://github.com/qooxdoo/qooxdoo-compiler/blob/master/source/class/qx/tool/compiler/targets/BuildTarget.js ? Would it make sense to factor out some stuff there that could be then be overridden?

**Comment by hkollmann** [comment]
> It has just been brought up on the main chat that source maps leak information on paths on the development machine. They should be excluded from the deployed source code bundle.

That's seems to be a bug. I never saw this

**Comment by cboulanger** [comment]
It's in the source maps. That's why they need to be stripped from the build files.

**Comment by hkollmann** [comment]
You are right. Overriding BuildTarget should work.

**Comment by cboulanger** [comment]
This deploy target could also minimize the number of files - preferrably just one javascript file plus the resources.

**Comment by cboulanger** [comment]
Ideally, the deploy target never produces the source map files in the first place instead of stripping them out afterwards - this should save a bit of time?

**Comment by derrell** [comment]
Wait... That source map is necessary on the target machine. Otherwise, you can't figure out where the error is really occurring from the browser.

**Comment by cboulanger** [comment]
But if the sources are not available - which they aren't in a deployment scenanrio - a source map doesn't make sense, does it? I would think that if an error occurs that cannot be figured out in a deploy build, you have to locally debug it in a "build" build with the sources present.

**Comment by derrell** [comment]
No. If I can find out at the browser where the error is occurring, I can look at my sources. In my case, the only environment that works is "build" as the app needs to establish websockets so is tested in a (development) true deployment. But an app could "phone home" and report an error including where it occurred, and someone could fix it and build a new version, too. @johnspackman indicated that he uses this feature at customer sites as well.

**Comment by johnspackman** [comment]
That's right, but the problem with sourcemaps is that in an untrusted environment the sourcemaps have the side effect of leaking information about file names and directory structures; although this is minor, it is worrying because ultimately it is leaking private data.

The original issue is that users look at the target output directory and see a massive bunch of files, and it is not clear what they need to deploy (and could reasonably assume it's everything, which is massive).

On reflection, I don't think that we want a separate "deploy" target because that would just duplicate all the massive number of files in the "build" target ("source" target is similarly large, with its own resources and transpiled directories).  Also, the "build" target is what the developer is likely to be testing against, and also what is likely to be deployed (with source maps) onto private testing servers.

When releasing to the end users, it is not a good idea to introduce a whole new build process *which is effectively untested*.  That's really crucial for repeatable testing, you *only* deploy the version that was on the testing server, you do not recompile because eventually something *will* go wrong.  

Our goal here is just to simplify the deployment process, and make sourcemaps something that you can turn on/off.  As sourcemaps are being suppressed for security concerns, but OTOH sourcemaps are so very useful, IMHO you should have to them turn on explicitly, but the deploy would issue a warning if you do not turn it on.

This would suggest that `qx deploy` runs the compilation process for `qx compile --target=build` and then copies the relevant files into the deployment directory (because the build compilation is very expensive, this would benefit from making sure that the compiler only actually runs & minifies etc if the code has changed).

**Comment by cboulanger** [comment]
I'd say we create a default "deploy" target without source maps. Anyone who wants to continue to use them can use the "build" target as before. I find it important, also for PR reasons, to have a compile target which is as small as possible, and has as few files as possible. There have been many requests for that on the main chat and I think that is an important selling point.

**Comment by cboulanger** [comment]
...just saw @johnspackman's post - `qx deploy` is fine for me too, although I like the idea of a separate target better since it fits well into our current design and can be realized without extending the API.

**Comment by johnspackman** [comment]
I'm going to try and work on this today, along with combining output into a single file (famous last words... :sigh: 😉)
