### ISSUE TITLE
qxcompiler can not compile itselfs any longer

### ISSUE THREAD

**Issue by hkollmann** [qooxdoo/qooxdoo-compiler#450]
How to reproduce:

git clone https://github.com/qooxdoo/qooxdoo-compiler.git
cd qooxdoo-compiler
npm install
./cqx compile

get's 
Error: TypeError: fixLibraryPath(...).then is not a function
    at qx.tool.utils.files.Utils.correctCase.then.then.then.data (/mnt/c/_vza/@repos/github.linux/qooxdoo-compiler/source/class/qx/tool/compiler/app/Library.js:174:14)

**Comment by johnspackman** [comment]
There is [a bug here in app/Library.js](https://github.com/qooxdoo/qooxdoo-compiler/blob/master/source/class/qx/tool/compiler/app/Library.js#L160) where the code should return `qx.Promise.resolve(dir)` instead of just `dir` - I'll submit a PR for that in a moment because another issue that missing source or resource dirs are not handled very elegantly.

However, the underlying cause is a bigger problem - the missing files are `node_modules/@qooxdoo/framework/{source,resource}`, but this is because the directory structure is now `node_modules/@qooxdoo/framework/framework/{source,resource}` - is the build process for `@qooxdoo/framework` broken?

**Comment by johnspackman** [comment]
Something odd that's happening on my Mac is that I although the directory structure is the same as on my Windows VM, `./qx compile` works - I'm presuming for the moment that is something to do with my dev setup

**Comment by hkollmann** [comment]
I will check this.

**Comment by hkollmann** [comment]
qooxdoo sources should be in node_modules/@qooxdoo/framework/framework/{source,resource}.
node_modules/@qooxdoo/framework is the root of the package and contains tool, lib, doc and framework folder.

**Comment by hkollmann** [comment]
We could/should change this during building. We can copy framework/source to source and include source to the npm file. This would make the package structure much more clearly.
What do you think?

**Comment by johnspackman** [comment]
yes I agree - there is currently a `node_modules/@qooxdoo/framework/Manifest.json` *and* `node_modules/@qooxdoo/framework/framework/Manifest.json` which is confusing, but IMHO either the first one needs a correct path in it's `provides.class` or the whole tree should be moved up (whcih would be preferable) and then `qx`'s auto-detect for the framework would work just like it does for any other directory which contains a library

**Comment by hkollmann** [comment]
I will prepare a PR for deploy_npm in the evening

**Comment by hkollmann** [comment]
done with #9707
