### ISSUE TITLE
scramble private method names (__methodName)

### ISSUE THREAD

**Issue by oetiker** [qooxdoo/qooxdoo-compiler#476]
I just ran into a case in our inhouse code where people were happily calling `__privateMethods` from the parent in a child class ... it would be really good if the compiler could start scrambling these names asap ... or we will have a major issue at our hands re-introducing this later on ...

**Comment by hkollmann** [comment]
You can activate a lint rule to check this: @qooxdoo/qx/no-illegal-private-usage 
It's not on by Default because it's very very slow.
Source is here https://github.com/qooxdoo/eslint-qx-plugins.

**Comment by hkollmann** [comment]
@oetiker: I refactored the no-illegal-private-usage rule a little bit so that is usable now.
Could you try if it is working for you? 
Here is the PR to update the compiler.

**Comment by oetiker** [comment]
the problem is that if we do this with the linter only, people will still use __ accessors, maybe just eslint exceptions to their code. @johnspackman is there anything hindering the compiler from scrambling the names as the old compiler used to.

**Comment by hkollmann** [comment]
IMHO that is some sort of organization to forbid this, is'nt it? Problem with scrambling is - also in the old compiler - that you get the errors only with builds - not with debug code.
I often had this problem by myself. 
Therefore i like the no-illegal-private-usage rule. Just fixed my own code and the compiler code see https://github.com/qooxdoo/qooxdoo-compiler/pull/481

Most errors in compiler and my was the missing of the declaration of the private members.

**Comment by oetiker** [comment]
private members are a feature that had been present in qooxdoo oo for a long time ... and yes the old compiler did not do it in source mode, but now with the new compiler, we can do this ... since the code does always get compiled. Scrambling I guess will also take care of the problem that a private property in the child should NOT affect a private property of the same name in the parent.

**Comment by johnspackman** [comment]
@oetiker 's right, it's something that the generator used to do and which I've always kind of planned but never got round to.

Part of the reason for my reticence was the effort it takes to correctly statically analyse code, but thinking about now there might be an easier option: for any variable prefixed with `__`, just rename it to `__` plus a random ID which is pseudo-unique (enough to avoid collisions most of the time).  This would be little more than a search & replace without analysing the context of the reference (which might be what the generator used to do).

Sometimes strings have to be mapped too - eg `this.disposeObjects("__myPrivateVar")` is a common example.

I agree it should work in source mode too - although in source mode that the unique ID should be a suffix rather than a replacement for debugging.
