### ISSUE TITLE
problem with externalResources

### ISSUE THREAD

**Issue by hkollmann** [qooxdoo/qooxdoo-compiler#628]
Consider the case you have 2 applications in compile.json:
one browser app and one node app.
The browser app needs some externalResources which will not work in an node enviroment.

Because externalResources are loaded from manifest.json for all applications you get an problem in this case.

Any ideas how to solve this?

Add an externalResources entry to the application in compile.json?=

Other ideas?

**Comment by cboulanger** [comment]
An `externalResources` entry to the application in compile.json sounds like a good idea.  Alternatively, we add a `platform` entry to `info` and when it is `node`, the compiler ignores the `externalResources` key? Since on node, all "external resources" can be required by the code itself - the compiler doesn't need to do anything here.

**Comment by cboulanger** [comment]
We still have the [`provides.type`](https://github.com/qooxdoo/qooxdoo-compiler/blob/master/source/resource/qx/tool/schema/Manifest-1-0-0.json#L183) key in the Manifest schema even though it doesn't do anything at the moment, maybe this can be used to configure a "hybrid" app. Although we talked about removing the key from the schema altogether since it has become without use.

**Comment by johnspackman** [comment]
applications already have a type (`"browser"`, `"node"`, or `"rhino"`) so we could exclude `externalResources` automatically on non-browser builds.

**Comment by hkollmann** [comment]
Are you shure that all external resources can be required by the code itself? Is this valid for rhino too?

If yes the easiest way is to remove the   urisBefore  entries from the templates - like the cssBefore entry.

**Comment by johnspackman** [comment]
in Rhino, I have a custom loader function - a bit like `require()` which allows code to be loaded from the filing system on demand; the loader generator by the application uses it to load all the app scripts, just like require.

Also, when booting up a rhino or node application, the developer has to choose the boot script, ie has control over loading before the rest of the app.

**Comment by hkollmann** [comment]
Done with https://github.com/qooxdoo/qooxdoo-compiler/pull/627
