### ISSUE TITLE
The qx.debug setting in the environment should be false when compiling the build target

### ISSUE THREAD

**Issue by andriy-s** [qooxdoo/qooxdoo-compiler#663]
The `qx.debug` setting in the environment seems to be always `true` by default, no matter what target is being compiled. While explicitly overriding it in the `compile.json` for a specific target works for me, it should instead be implicitly false for the `build` target.

**Comment by cboulanger** [comment]
I have no strong opinion on this. You have a point, but since it is very easy to override the setting in `compile.json`, I wonder if it necessary to change it. After all, this will change the behavior of the compiler and lead to people wonder why they don't get debug messages anymore in their builds.

**Comment by johnspackman** [comment]
Im more inclined to add it in as a default, partly because that's how the generator worked but mostly that people won't necessarily know that's what they have to do in order to strip out unnecessary code.  It can make a big difference to the size also, because by eliminating debug code, the list of dependent classes can reduce as well.
