### ISSUE TITLE
Compiler ignores @qooxdoo/framework

### ISSUE THREAD

**Issue by oetiker** [qooxdoo/qooxdoo-compiler#748]
the compiler from 2020-08-03 still comes with qooxdoo from june. So I used `npm i @qooxdoo/framework` to get a current copy of qooxdoo ... it installs fine, but that library search path of the compiler seems to be such that ignores the explicitly installed framework and only uses it's internal one.

**Comment by cboulanger** [comment]
Is that even if you set `npx qx config set qx.framework path/to/framework`? Because that's the way to tell the compiler to use a different framework than the one that comes shipped with it. 

That the compiler comes with an old version must be a bug.

**Comment by oetiker** [comment]
> Is that even if you set `npx qx config set qx.framework path/to/framework`? Because that's the way to tell the compiler to use a different framework than the one that comes shipped with it. `npm install`ing a different framework doesn't do anything, that's on purpose.
> 
> That the compiler comes with an old version must be a bug.

well what happens now, is that if you install a different version of the framework using npm the compiler seems to use it as a `fallback` so I can now include the tangible theme but when I try using it, things fail because for all classes that are in the co--packaged version of the framework, the compiler uses those instead of the version that I explicitly installed

**Comment by cboulanger** [comment]
@johnspackman @hkollmann Can you comment? That's certainly not the way it _should_ behave...

**Comment by hkollmann** [comment]
Will Check ist in the Morning 

Von meinem iPhone gesendet

**Comment by oetiker** [comment]
@cboulanger  this seems not to work

```console
oetiker>npx qx config set qx.framework node_modules/@qooxdoo/framework
Warning: Unrecognised configuration key qx.framework

oetiker>npx qx help

qooxdoo command line interface
==============================
Versions: @qooxdoo/compiler    v1.0.0-beta
          @qooxdqxoo/framework v6.0.0-beta-20200803-1413
```

**Comment by cboulanger** [comment]
Sorry, it's `qx.library`, wasn't looking it up: https://qooxdoo.org/documentation/#/development/cli/commands?id=persistent-configuration

Try `npx qx config list` to see the (yet very short) list of config variables. 

We should document this better, it's not easy to find in the docs.

**Comment by cboulanger** [comment]
Can you add something to the documentation, @oetiker - as you would like to find it when you had the problem.

**Comment by johnspackman** [comment]
> @johnspackman @hkollmann Can you comment? That's certainly not the way it _should_ behave...

Up until recently, it was a requirement that the compiler shipped with the `@qooxdoo/framework` because it needed it at runtime just to execute, but a recent PR meant that the compiler compiles itself prior to release and therefore ships with the minimal set of classes and resources that it requires (ie it is itself a normal compiled app).

However, the compiler does still need the full `@qooxdoo/framework` when compiling projects which do not have an explicit `@qooxdoo/framework` listed in `package.json` - ie the "fallback" position.  Currently, the dependency on `@qooxdoo/framework` is mandatory just to simplify deployment, but this could be optimised at some point where the compiler downloads the framework into a directory underneath `~/.qooxdoo/` the first time that it is needed - with the regular checks for upgrades etc etc

> `npx qx config set qx.framework node_modules/@qooxdoo/framework`

This should not be necessary and should be the default - ie if the current project has `node_modules/@qooxdoo/framework/` then it should be used automatically for compiling the current app (although the compiler will not use it to execute itself).

The reason that there is a error message is because the correct key is `qx.library`, eg:
`npx qx config set qx.library node_modules/@qooxdoo/framework`

You can see the complete list with `npx qx config list --all`

**Comment by oetiker** [comment]
Thank you @johnspackman exactly as I would expect it.

1. when I install @qooxdoo/compiler then the compiler relies on its internal copy of qooxdoo
2. If I install @qooxdoo/framework additionally it will use that instead
3 if I want to use some other source I would set it using `npx qx config set qx.library my-other/path/to/qx/framework`

at the moment it seems that the compiler is using a search path for the qooxdoo framework wich starts with the internal copy and then goes to the toplevel copy ... this is unfortunate as it can lead to mixing components from the two copies of qooxdoo ... 

I think it should rather use one or the other ...

**Comment by oetiker** [comment]
On another note, regarding the persistant configuration ... since it is stored in my `~/.qooxdoo` directory it is not realy helpful at all for this purpose since I have many different projects with different levels of qooxdoo/compiler so all configuration must be project specific ... so I would store any special library configuration in the compile.json file anyway

**Comment by hkollmann** [comment]
```
C:\temp\test>npx qx compile -v
QooxDoo found in C:\temp\test\node_modules\@qooxdoo\framework
```

Seems to be working now.

**Comment by cboulanger** [comment]
@oetiker can your review and close if you problem is solved?

**Comment by oetiker** [comment]
seems to work now ... thanks!
